<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DT-TECH-2D80" name="testCases.DatabaseCheck" tests="166" failures="7" timestamp="23 Feb 2018 09:47:47 GMT" time="173.693" errors="3">
  <testcase name="loginTest" time="1.038" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.056" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.045" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.054" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.040" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.047" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.047" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.039" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.038" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.040" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.045" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.047" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.035" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.045" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.061" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:241)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.050" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.038" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.045" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.047" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.067" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.047" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.039" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.050" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.039" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.050" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:241)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.040" classname="testCases.DatabaseCheck">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:241)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:241)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.036" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.040" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.035" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.509" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.035" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.053" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.047" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.039" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.006" classname="testCases.DatabaseCheck">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseDE1(AppKeywords.java:513)at testKeywords.Keyword.executeKeywords(Keyword.java:218)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.005" classname="testCases.DatabaseCheck">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseDE1(AppKeywords.java:513)at testKeywords.Keyword.executeKeywords(Keyword.java:218)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.037" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.055" classname="testCases.DatabaseCheck">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:241)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.034" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:241)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.039" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.051" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.040" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck">
    <failure type="java.lang.AssertionError" message="FAIL">
      <![CDATA[java.lang.AssertionError: FAILat org.testng.Assert.fail(Assert.java:96)at testKeywords.Keyword.executeKeywords(Keyword.java:241)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.005" classname="testCases.DatabaseCheck">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseDE1(AppKeywords.java:513)at testKeywords.Keyword.executeKeywords(Keyword.java:218)at testCases.DatabaseCheck.loginTest(DatabaseCheck.java:39)at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.050" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.058" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.052" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.054" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.050" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.065" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.053" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.035" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.053" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.050" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.052" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.051" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.045" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.045" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.046" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.042" classname="testCases.DatabaseCheck"/>
  <testcase name="loginTest" time="1.043" classname="testCases.DatabaseCheck"/>
</testsuite> <!-- testCases.DatabaseCheck -->
