<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DT-TECH-2D80" name="testCases.DataEntry2" tests="3" failures="1" timestamp="14 Mar 2018 04:30:34 GMT" time="137.152" errors="0">
  <testcase name="loginTest" time="0.015" classname="testCases.DataEntry2">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="0.003" classname="testCases.DataEntry2">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="137.134" classname="testCases.DataEntry2">
    <failure type="java.lang.AssertionError" message="Failure in extracting the locator --.//*[contains(@id,&#039;ContentPlaceHolder1_ddlNationality&#039;)]">
      <![CDATA[java.lang.AssertionError: Failure in extracting the locator --.//*[contains(@id,'ContentPlaceHolder1_ddlNationality')]at org.testng.Assert.fail(Assert.java:96)at testKeywords.GenericKeywords.getElement(GenericKeywords.java:283)at testKeywords.GenericKeywords.dropDown(GenericKeywords.java:142)at testKeywords.Keyword.executeKeywords(Keyword.java:104)at testCases.DataEntry2.loginTest(DataEntry2.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- testCases.DataEntry2 -->
